###################  项目启动端口  ###################
server:
  port: 38081
  
security:
 basic:
   enabled: false
management:
 security:
  enabled: false

###################  dsf配置  ###################
dsf:
 register:
  host: 127.0.0.1
  port: 8500


###################  spring配置  ###################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activity?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: frike
    password: 1234
    
mybatis:
  mapperLocations: classpath:META-INF/mybatis/*/*.xml    
      
